### ISSUE TITLE
NBitcoin 6.0.8 can't build for Android. Linker issue

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/NBitcoin#1048]
Hello there!
I updated NBitcoin 5.0.83 to 6.0.8 for Xarmarin.Forms project & it stopped building for Android with error:
`##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(643,5): Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'NBitcoin.Script NBitcoin.Altcoins.BCash/BTrashPubKeyAddress::GeneratePaymentScript()' in assembly: 'NBitcoin.Altcoins.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve NBitcoin.Script NBitcoin.TxDestination::get_ScriptPubKey()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() `
It would be great to get it fixed.
Does anybody have ideas on how to fix it?
Thank you in advance!

**Comment by NicolasDorier** [comment]
hi @ArtjomP .  You need to rebuild `NBitcoin.Altcoins.dll` as well.

**Comment by ArtjomP** [comment]
Thank you @NicolasDorier . 
I don't use NBitcoin.Altcoins explicitly. NBitcoin uses from the Nuget [NBitcoin.Altcoins](https://www.nuget.org/packages/NBitcoin.Altcoins/) 
I could update it myself and upload to a private feed but I would wait for the official version.

Have a good time!

**Comment by NicolasDorier** [comment]
@ArtjomP that's weird, NBitcoin.Altcoins is up to date on the nuget.

**Comment by NicolasDorier** [comment]
I think the problem is more related to some cache from xamarin or something like that.

**Comment by ArtjomP** [comment]
Thank you for your reply. 
It does not look like the cache problem because we use MS agents and they start building from the scratch.
It was QBitninja that caused the issue.
Have a great time!

**Comment by NicolasDorier** [comment]
@ArtjomP ah I was not expecting QBitNinja to still be used. I will try to publish a new version.

**Comment by NicolasDorier** [comment]
@ArtjomP I published version 1.0.4 of the QBitNinja.Client library built against latest version of NBitcoin.
