### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void NBitcoin.BitcoinStream.ReadWrite(!!0 ByRef)'

### ISSUE THREAD

**Issue by konstiantyn** [MetacoSA/NBitcoin#1080]
[2022-01-11 09:52:33.8559] [E] [zec] Error during UpdateJob System.MissingMethodException: Method not found: 'Void NBitcoin.BitcoinStream.ReadWrite(!!0 ByRef)'.
   at NBitcoin.Zcash.ZcashTransaction.ReadWrite(BitcoinStream stream)
   at Miningcore.Blockchain.Equihash.EquihashJob.BuildCoinbase() in /home/dev/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 175
   at Miningcore.Blockchain.Equihash.EquihashJob.Init(EquihashBlockTemplate blockTemplate, String jobId, PoolConfig poolConfig, ClusterConfig clusterConfig, IMasterClock clock, IDestination poolAddressDestination, Network network, Equih$
   at Miningcore.Blockchain.Equihash.EquihashJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json) in /home/dev/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJobManager.cs:line 132    at NBitco$
   at Miningcore.Blockchain.Equihash.EquihashJob.BuildCoinbase() in /home/dev/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJob.cs:line 175
   at Miningcore.Blockchain.Equihash.EquihashJob.Init(EquihashBlockTemplate blockTemplate, String jobId, PoolConfig poolConfig, ClusterConfig clusterConfig, IMasterClock clock, IDestination poolAddressDestination, Network network, Equih$
   at Miningcore.Blockchain.Equihash.EquihashJobManager.UpdateJob(CancellationToken ct, Boolean forceUpdate, String via, String json) in /home/dev/miningcore/src/Miningcore/Blockchain/Equihash/EquihashJobManager.cs:line 132

**Comment by knocte** [comment]
You upgraded to new version of NBitcoin recently, right?

**Comment by konstiantyn** [comment]
Yes. right

**Comment by knocte** [comment]
Then somewhere you're still using the old version of NBitcoin without knowing it.

**Comment by knocte** [comment]
Maybe you didn't update it in all projects of the solution?

**Comment by konstiantyn** [comment]
I'm using it.
https://github.com/LykkeCity/NBitcoin.Zcash
