### ISSUE TITLE
RPCClient.GetBlock (for Litecoin network) method throws when passing block number 2265984

### ISSUE THREAD

**Issue by CoinmaniaExchange** [MetacoSA/NBitcoin#1125]
When calling an RPC function on a node running Litecoin Core 0.21.2 ([a major update](https://github.com/litecoin-project/litecoin/releases/tag/v0.21.2)) the `GetBlock` method throws `System.FormatException`. Starting from this major update a new `mweb` field is returned in the response JSON object. Litecoin is no longer compatible with the Bitcoin wire protocol Blockbook uses to deserialize block data. The details of the exception are as follows:
<br>
``System.FormatException
  HResult=0x80131537
  Message=Unknown transaction optional data
  Source=NBitcoin
  StackTrace:
   at NBitcoin.Transaction.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
   at NBitcoin.BitcoinStream.ReadWrite[T](List`1& list)
   at NBitcoin.Block.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, ConsensusFactory consensusFactory, Nullable`1 version)
   at NBitcoin.Block.Parse(String hex, ConsensusFactory consensusFactory)
   at NBitcoin.Block.Parse(String hex, Network network)
   at NBitcoin.RPC.RPCClient.<GetBlockAsync>d__106.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBitcoin.RPC.RPCClient.GetBlock(uint256 blockId)``
<br>
Are you planning to take into account the above change in the library?

**Comment by twilightrus** [comment]
+1

**Comment by NicolasDorier** [comment]
making new version with the fix

**Comment by NicolasDorier** [comment]
Pushed on 3.0.15, reopen if still an issue, didn't test it
