### ISSUE TITLE
NBitcoin.uint256.Comparison throws exception

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#227]
Seem to randomly happen, and a restart of the FullNode continue normally.
Any idea?
```
FullNode[0]
      Consensus loop unhandled exception (Tip:81653)
System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.uint256.Comparison(uint256 a, uint256 b)
   at NBitcoin.BlockHeader.CheckProofOfWork()
   at Stratis.Bitcoin.Consensus.ConsensusValidator.CheckBlockHeader(BlockHeader header) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusValidator.cs:line 61
   at Stratis.Bitcoin.Consensus.ConsensusLoop.AcceptBlock(BlockResult result) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 189
   at Stratis.Bitcoin.Consensus.ConsensusLoop.ExecuteNextBlock(CancellationToken cancellationToken) in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 176
   at Stratis.Bitcoin.Consensus.ConsensusLoop.<Execute>d__24.MoveNext() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\Consensus\ConsensusLoop.cs:line 133
   at Stratis.Bitcoin.FullNode.RunLoop() in C:\Users\Dan\Documents\GitHub\StratisBitcoinFullNode\Stratis.Bitcoin\FullNode.cs:line 292
```

**Comment by NicolasDorier** [comment]
wow. This is very very very strange. I will try to push a new version on NBitcoin I have an idea why.

**Comment by NicolasDorier** [comment]
try to update to 3.0.2.10 and let me know.

**Comment by dangershony** [comment]
Ok I will try thanks

**Comment by dangershony** [comment]
Looks like this is fixed, I will let the node run over night and reopen if any issues.
