### ISSUE TITLE
How to subtract fee from amount to send , with builder ?

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [MetacoSA/NBitcoin#480]
``` 
var builder = new TransactionBuilder();
                    var transaction = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SubtractFees()
                        .SetChange(_serviceAccount)  
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(true);

``` 
Error in builder.Check(transaction); - > {Fee too low, actual is 0.00000444, policy minimum is 0.00000445}

**Comment by Ilchuk-Mihail** [comment]
``` 
var builder = new TransactionBuilder();
                    var transaction = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SubtractFees()
                        .SetChange(_serviceAccount)  
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(true);

``` 
Error in builder.Check(transaction); - > {Fee too low, actual is 0.00000444, policy minimum is 0.00000445}

**Comment by Ilchuk-Mihail** [comment]
I estimate fee , but it's not enough( Same error -> {Fee too low, actual is 0.00000444, policy minimum is 0.00000446}
```
                 var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
                    var fee = builder.EstimateFees(unsignedTx, rate.FeeRate);
```

**Comment by felipegtx** [comment]
@Ilchuk-Mihail I might be wrong but I think that you should use either `SubtractFees` or `SendEstimatedFees`. 

One is probably overriding the value of the other. I'd suggest you to try to remove `SendEstimatedFees` and see how it goes.

**Comment by NicolasDorier** [comment]
ha this is interesting, this might be a bug. Are you using the latest version?

**Comment by NicolasDorier** [comment]
@felipegtx no, SubstractFee indicate where to substract the fees, and SendEstimatedFees are actually sending them.

**Comment by NicolasDorier** [comment]
@Ilchuk-Mihail can you give me all your scriptCoins so I can replicate the problem?

**Comment by NicolasDorier** [comment]
Also what is the `rate.FeeRate` value?

**Comment by Ilchuk-Mihail** [comment]
Yes. I Use latest version.

I tried to sign a transaction, then calculate size of transaction    var size = signedTx.GetVirtualSize();
Next calculate fee. 
` var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);`
` var fee = builder.EstimateFees(unsignedTx, rate.FeeRate);`

and again sign 

But, Fee Size 2.99 sat/B ,  not 1 
[(https://testnet.smartbit.com.au/tx/29c6fcad8940875c6306ab6dc82bf0cb89269e960649086bd184012408674a0d)
](https://testnet.smartbit.com.au/tx/29c6fcad8940875c6306ab6dc82bf0cb89269e960649086bd184012408674a0d)

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier  `rate.FeeRate ={1 Sat/B}`

**Comment by NicolasDorier** [comment]
what is the redeemScript?

**Comment by NicolasDorier** [comment]
Is is segwit?

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier  I use multi sig addresses/ All adresses in transaction it's multi sig 3 of 3.

``` 
  foreach (var coin in unspentCoins)
            {
                var redeemScript = redeemScripts[coin.Address.ToString()];
                var scriptCoin = coin.AsCoin().ToScriptCoin(redeemScript);
                scriptCoins.Add(scriptCoin);
            }

var reedemScript = PayToMultiSigTemplate
                    .Instance
                    .GenerateScriptPubKey(3, keysForAddress.ToArray());```

**Comment by NicolasDorier** [comment]
Thanks, looking at it now. I guess I estimate fee wrong. Will fix in the hour.

**Comment by NicolasDorier** [comment]
I confirm the bug, could reproduce, trying to fix it (not easy one)

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier  It's very bad. Is it coming out to fix?

**Comment by NicolasDorier** [comment]
Yes, will fix today.

**Comment by NicolasDorier** [comment]
@Ilchuk-Mihail I fixed it on version 4.1.1.28, can you give a try?

**Comment by Ilchuk-Mihail** [comment]
Ok. I will try now.

This code is correct ? 
      **.SendFees(fee) 
.SubtractFees()**

```
    var builder = new TransactionBuilder();
                    var unsignedTx = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SetChange(_serviceAccount)
                        .BuildTransaction(false);


                    //estimate fee
                    var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
                    var fee = builder.EstimateFees(unsignedTx, rate.FeeRate);

                    var signedTx = builder
                        .SendFees(fee)
                        .SubtractFees()
                        .BuildTransaction(sign: true);
```

**Comment by NicolasDorier** [comment]
no.

**Comment by Ilchuk-Mihail** [comment]
ok. 
Now i got this error Message = "A change address should be specified (Uncolored)"

_serviceAccount - it's multi sig address (2Mx4q6qM6jEAsZEWES6Dev7bNrKT6bMBxhh)

**Comment by NicolasDorier** [comment]
Sorry, invert SetChange and SendEstimatedFee.

**Comment by NicolasDorier** [comment]
```
var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
 var signedTx = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SubtractFees()
                        .SetChange(_serviceAccount)
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(true);
```

**Comment by Ilchuk-Mihail** [comment]
this address the same format ?

```
 //create 3 of 3 multi sig address
            var scriptPubKey = PayToMultiSigTemplate
                .Instance
                .GenerateScriptPubKey(3, generatedKeys);

            //var address1 = scriptPubKey.Hash.GetAddress(_network); 
 //{2Mx4q6qM6jEAsZEWES6Dev7bNrKT6bMBxhh}
            var address = scriptPubKey.WitHash.ScriptPubKey.Hash.ScriptPubKey.GetDestinationAddress(_network);  //{2NEt3Vxfzm5DFX81LPf5bJbXA9REERtyRjb}
```

**Comment by NicolasDorier** [comment]
yep, give it a try. Should work, instant profit.

**Comment by Ilchuk-Mihail** [comment]
I create two new addresses  P2WSH . Send some coins on them.

```

{
  "hash": "659ab17af0eed0d81a73e96d9a2a0c2db4e81d0dad035a1bcd9429d6e214c493",
  "ver": 1,
  "vin_sz": 3,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 1282,
  "in": [
    {
      "prev_out": {
        "hash": "756162f78fb3c357233db24c56a549f4a2f0ffd9db4e515c1d534127b49c7f0b",
        "n": 1
      },
      "scriptSig": "0020e926480b89275a3801e83798ce7eb17838d5a2e5db4bd1684204fc378a213062",
      "witness": "0 3045022100d4503584b04e6a3607cb6c856043db9f9bea1a0020d84c57fd3ac7a2dcac8c0002200e590a1d030d3136cc0da83392261f1da3b0bd0ad113df34e3e3741fd8491c8f01 304402200b355d8ed9e3eabb794f2e5e1a5f2a760162fda168cdfea054093f60a2941b81022053311c396128ebf1c7c931dbaeebc1b831c8caf135d48e612a68e4f1b2fd824b01 3044022074b3c1129f17b4f2d264aac356f36f3959e0f90212409924b8958fad3da1591e02203cec471a5894fa24e83b17d7a984c2d509d1b7e20dd4daba2c2a7febadc0464801 532103927efb3e7fe9e26294bbb22d0a8173bc920486a7fd386b04f1a9243d7e808f08210303c494b71133be85eb36c215e205a01fc8c2d769f718cdb2d19b3b9a0b5745332102b2f900c859d1c3fe75120b524a30e42b0f9e58db48472079a32dca444dfed12f53ae"
    },
    {
      "prev_out": {
        "hash": "3482b52b6ed543146b55dd1a1162cd2b9ce4c1bebdefe24985943ff3466ee712",
        "n": 0
      },
      "scriptSig": "0020e926480b89275a3801e83798ce7eb17838d5a2e5db4bd1684204fc378a213062",
      "witness": "0 30440220133bab8e6c9027c42a765698429e8486ea7010278a29a845cd00873bc0b020f1022067dc5548fd8b6c283697b9594f4fa588054e9957e9dc57ae4d71ff58a84d93ec01 30440220589ab955c6ed9c0255a43fbf03aba9c3b8ab5903a420800f89b171ff26d51ae20220265f62687dfb1b31a1d6b1b3e59464d3d5339d621d38807c58000594d2765bb301 3045022100c2a1247d0ca27d866a884b4e03e1f6606121d07569fb17e4169e7450fdea510502206d984196e642bb694c01fc6bdcf1490e366f5332a28ff353fc50392448cc989201 532103927efb3e7fe9e26294bbb22d0a8173bc920486a7fd386b04f1a9243d7e808f08210303c494b71133be85eb36c215e205a01fc8c2d769f718cdb2d19b3b9a0b5745332102b2f900c859d1c3fe75120b524a30e42b0f9e58db48472079a32dca444dfed12f53ae"
    },
    {
      "prev_out": {
        "hash": "ebf3a724f715d0657d680eb280d58d39e92ba4f17548480fcbac0824e1db5245",
        "n": 1
      },
      "scriptSig": "0020e926480b89275a3801e83798ce7eb17838d5a2e5db4bd1684204fc378a213062",
      "witness": "0 304502210082616c6e2a053bd14aad7f458f84b63edf0c5bb9c00f028ce7755c038f83e74e02207ea50627927a17bb6ccc3d639fa20446f53a4b4318aba451c9843af7721f459401 304402206f460a9c95cb04a575959753800a4d26e16cce40419a31d906a1b2586c40debc0220525cffa3894077c77be88ed5c3ce23669b8632575194997270cbe0c269dfecb901 3045022100943d2ba3c8c996b442859847aff163748824c5129198eb2f713db21c8f13518502204e99cd4d8da67aaf299bc9e848c67af6218dc8de9c8c6dfb7d069a37a365da0601 532103927efb3e7fe9e26294bbb22d0a8173bc920486a7fd386b04f1a9243d7e808f08210303c494b71133be85eb36c215e205a01fc8c2d769f718cdb2d19b3b9a0b5745332102b2f900c859d1c3fe75120b524a30e42b0f9e58db48472079a32dca444dfed12f53ae"
    }
  ],
  "out": [
    {
      "value": "0.00020400",
      "scriptPubKey": "OP_HASH160 34e15d388bc16630615b7c10f9a6af0957d67bc5 OP_EQUAL"
    },
    {
      "value": "0.00099448",
      "scriptPubKey": "OP_DUP OP_HASH160 a9992498c49512ef23b2348d6fe235b45a16c23a OP_EQUALVERIFY OP_CHECKSIG"
    }
  ]
}

```

Transction size -  "size": 1282,
var size = signedTx.GetVirtualSize();  - 549

{Fee too low, actual is 0.00000552, policy minimum is 0.00001282}

**Comment by NicolasDorier** [comment]
it is not possible, can you show me your code.

**Comment by NicolasDorier** [comment]
Do not add fee manually, you will mess up. 

```
var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
 var signedTx = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SubtractFees()
                        .SetChange(_serviceAccount)
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(true);
```

**Comment by Ilchuk-Mihail** [comment]
```
var unspentCoins = await GetUnspentCoins(amount); //gets input from node 

 var redeemScripts = new Dictionary<string, Script>();
 var privateKeys = GetPrivateKeys(masterKeys, keyPath, ref redeemScripts);
 var scriptCoins = GetScriptCoins(unspentCoins, redeemScripts);


//get GetScriptCoins function

   foreach (var coin in unspentCoins)
            {
                var redeemScript = redeemScripts[coin.Address.ToString()];
                var scriptCoin = coin.AsCoin().ToScriptCoin(redeemScript);
                scriptCoins.Add(scriptCoin);
            }

//redeemScripts for each input 
 var reedemScript = PayToMultiSigTemplate
                    .Instance
                    .GenerateScriptPubKey(3, keysForAddress.ToArray());

var builder = new TransactionBuilder();
var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
                    var signedTx = builder
                        .AddCoins(scriptCoins)
                        .AddKeys(privateKeys.ToArray())
                        .Send(destanition, new Money(amount, MoneyUnit.BTC))
                        .SubtractFees()
                        .SetChange(_serviceAccount)
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(true);

 var txId = await SendRawTrasaction(signedTx); 
 var errors = builder.Check(signedTx);
```

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier Do not add fee manually, you will mess up.
I add it only for test.

I think maybe it's because I deleted wallet.dat and its first transactions 
don't know

1) I deleted wallet.dat
2) created 2 addresses -  3 of 3 multi sig P2WSH  
3) sent coins to them
4) created sending transaction 
and error :(

but, when it was P2SH, and I updated to version 4.1.1.28 . I had no errors, at least i didn't see one

**Comment by NicolasDorier** [comment]
your code seems OK. Will try it now.

**Comment by Ilchuk-Mihail** [comment]
The same (

{Fee too low, actual is 0.00000552, policy minimum is 0.00001286}

**Comment by NicolasDorier** [comment]
With P2SH it works?

**Comment by Ilchuk-Mihail** [comment]
Yes. Just tried.

[https://testnet.smartbit.com.au/tx/419e2097091193ee9c1a2d65e18827524b091efe5d7bb0893a4f94f5f59a869e](https://testnet.smartbit.com.au/tx/419e2097091193ee9c1a2d65e18827524b091efe5d7bb0893a4f94f5f59a869e)

**Comment by NicolasDorier** [comment]
you are correct. This is very strange, because this is something I use near everywhere.

**Comment by NicolasDorier** [comment]
Checking where it comes from

**Comment by NicolasDorier** [comment]
Wow, actually the transaction does not pass the Check, but it can be broadcasted. I can't believe such bug was around for long... doing a fix.

**Comment by NicolasDorier** [comment]
Please update to `4.1.1.30`, then your segwit version will work as expected. 

Thanks for those bug reports, I am very surprised that I had not encountered them before.

**Comment by knocte** [comment]
Hey Nicolas:

> When you generate addresses, you just need to use
> redeem.WitHash.ScriptPubKey.Hash.ScriptPubkey.GetAddress(Network.Main) instead of
> redeem.Hash.ScriptPubkey.GetAddress(Network.Main) if you use P2SH now.

I'm having a hard time understanding the above. Is it that P2SH is cheaper because it maps to bech32? Is Segwit-P2WSH always more expensive than Segwit-P2SH?
And why the recommended way is much harder to get (API-wise) than the unrecommended way? Shouldn't the latter be marked as deprecated with a warning message?

**Comment by NicolasDorier** [comment]
@Ilchuk-Mihail I added you, but I prefer you ask questions about NBitcoin as Issues as it get indexed by google and help other people as well.

**Comment by NicolasDorier** [comment]
@knocte  `redeem.WitHash.ScriptPubKey.Hash.ScriptPubkey.GetAddress(Network.Main)` is the P2SH Segwit , I advise this for now, as it is the most compatible with all wallets.

 `redeem.WitHash.ScriptPubKey.GetAddress(Network.Main)` is even cheaper, same code, but it uses bech32, which is not compatible everywhere yet.

**Comment by NicolasDorier** [comment]
The recommended way is harder because conceptually, it is harder.

If we break `redeem.WitHash.ScriptPubKey.Hash.ScriptPubkey.GetAddress(Network.Main)`

`redeem` is your real script.

`redeem.WitHash.ScriptPubKey` is the scriptPubKey for P2WSH

`redeem.WitHash.ScriptPubKey.Hash.ScriptPubkey` is the same P2WSH, but as a P2SH.

**Comment by NicolasDorier** [comment]
@Ilchuk-Mihail everything is fixed?

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier  Everything seems to work. Thanks. 

I have not fully understood the addresses. What, in my case, is better when I develop a wallet ?
P2SH-P2WSH or P2WSH ?

If I use P2WSH  (cheaper), will there be any problems transferring from other wallets to this address?

**Comment by NicolasDorier** [comment]
Yes, P2WSH is the cheapest, but the bech32 addresses are not supported by some services and wallet yet.
P2SH-P2WSH is a bit more expensive, but will work even with older service and wallet.

**Comment by sigHash** [comment]
Shouldn't SubtractFees() fail if amountToSend is below estimated transaction fee? 

```
                    var signedTx = builder
                        .AddCoins(scriptCoins)
                        .Send(destanition, amountToSend)
                        .SubtractFees()
                        .SetChange(changeAddress)
                        .SendEstimatedFees(rate.FeeRate)
                        .BuildTransaction(false);
```

I just created this transaction and when I [decode](https://live.blockcypher.com/btc/decodetx/) it  the output value is negative. 

`txHex = "01000000011e4b16bcc0f0a3b5a66850fcad95542cbea3473986de7d507ebd20857812d9f20000000000ffffffff02dd561e030000000017a9149a15ac8e50e4eb2758a519145332e67429377a8d87afe9feffffffffff17a9147603dde43286296e1332d050261f678afd50049d8700000000"`

**Comment by NicolasDorier** [comment]
@sigHash thanks, checking this now.

**Comment by NicolasDorier** [comment]
@sigHash fixed in 4.1.1.45 thanks for the report!

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/commit/7e3508c1f2ae88e76832ee619f9ebd9e05d801e8

**Comment by Ilchuk-Mihail** [comment]
In Bitcoin cash. 
Send transaction for this way not working . 

Error :
Message = "TX decode failed"
RPCCode = RPC_DESERIALIZATION_ERROR


What can it be wrong?

**Comment by sigHash** [comment]
@Ilchuk-Mihail Are you using NBitcoin.Altcoins? If you copy your code here we might be able to help

**Comment by Ilchuk-Mihail** [comment]
Yes, I use NBitcoin.Altcoins. 

The same code https://github.com/MetacoSA/NBitcoin/issues/480#issuecomment-406631619

It's working for Bitcoin and Litecoin, but not for Bitcoin cash. 


This is signed transaction, and bitcoin cash can't decode it. Not working SendRawTransaction 
```

{
  "hash": "77bf391c00cbe5a9ddf3c537503938130a1213d08f346ed61494d962bfc7b0cb",
  "ver": 1,
  "vin_sz": 1,
  "vout_sz": 2,
  "lock_time": 0,
  "size": 478,
  "in": [
    {
      "prev_out": {
        "hash": "0295a4531b6a75ae18f9402d41479d67d9b534f81f12b5f2395329d5f59b6467",
        "n": 1
      },
      "scriptSig": "0020935af413da734439ec5c375908862988879b92fe417d0dcaf3d2afab814b9914",
      "witness": "0 30450221009140ce900edfa86d8d25cca44de6a076d7ecc6b986555227c86a09e5b0eea4e602204533c71f71e33d5d289d405403162d6b38b5a6043f9249aa31ad681ffb05315601 3045022100cd073497f5f3f5cbe06adf923fd3667bee1ec48482c95dbd083be7587122a8f702205a45afaa3d62de9e58c598d439da219ca1c9010e1c3de78db09a58e82ce56d6d01 304402205c9a378c580175ee7ff0fabb232f38cd2ac3054b076c22d84c80b10ff82bdf47022043724ec50580ba3027e476500f92b5d5e4613749fc23a1f723465afbdf6c9f9001 5321038d9516d9e78b4574a610de1871053b7214bbeebcd4fa27ae861a5a30cede034b21035f5050d2749de2ac6af4faff1faa18cd7a4f70954ae0aa8e2ef451d7b8055e2621037c46991c070df7679ec6f3eb3ab604f04bc8a552a49dc2eb4dc75f3e206601e053ae"
    }
  ],
  "out": [
    {
      "value": "2.10000000",
      "scriptPubKey": "OP_HASH160 302b84d9d50c028a7b63d7c3584b7eb72f91c8eb OP_EQUAL"
    },
    {
      "value": "0.09999766",
      "scriptPubKey": "OP_HASH160 6aa9d0037407278ea788a57960efef90a2ebbc7d OP_EQUAL"
    }
  ]
}
```

**Comment by Ilchuk-Mihail** [comment]
Message = "TX decode failed"
RPCCode = RPC_DESERIALIZATION_ERROR
RPCCodeMessage = "Error parsing or validating structure in raw format"

**Comment by Ilchuk-Mihail** [comment]
@NicolasDorier  Will it help ?

**Comment by NicolasDorier** [comment]
BCash does not have segwit support, and you are using segwit in your transaction.

**Comment by Ilchuk-Mihail** [comment]
I need use first address1, for creating addresses ?
BCH - does not support P2SH-P2WSH and P2WSH (address3, address2)

For BTC, LTC i use address3.

var address1 = scriptPubKey.Hash.GetAddress(Network);
var address2 = scriptPubKey.WitHash.ScriptPubKey.GetDestinationAddress(Network); // P2WSH
var address3 = scriptPubKey.WitHash.ScriptPubKey.Hash.ScriptPubKey.GetDestinationAddress(Network); // P2SH-P2WSH

**Comment by NicolasDorier** [comment]
for bch yes, you need address1

**Comment by Ilchuk-Mihail** [comment]
Now error:
RPCCode = RPC_TRANSACTION_REJECTED
16: mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)
RPCCodeMessage = "Transaction was rejected by network rules"


I use the same code  and address1 - multisig

**Comment by Kukks** [comment]
might help: 
https://github.com/Bitcoin-ABC/bitcoin-abc/issues/174

**Comment by NicolasDorier** [comment]
@Ilchuk-Mihail you need to use `txBuilder.SetConsensusFactory(NBitcoin.Altcoins.BCash.Instance.Mainnet)`

**Comment by sixjac** [comment]
> ```
>  var rate = _rpcClient.EstimateSmartFee(6, EstimateSmartFeeMode.Conservative);
>  var signedTx = builder
>                         .AddCoins(scriptCoins)
>                         .AddKeys(privateKeys.ToArray())
>                         .Send(destanition, new Money(amount, MoneyUnit.BTC))
>                         .SubtractFees()
>                         .SendEstimatedFees(rate.FeeRate)
>                         .SetChange(_serviceAccount)
>                         .BuildTransaction(true);
> ```

Exception when changed to use the above code, stack trace:

 at NBitcoin.TransactionBuilder.BuildTransaction(TransactionBuildingContext ctx, BuilderGroup group, IEnumerable`1 builders, IEnumerable`1 coins, IMoney zero)
   at NBitcoin.TransactionBuilder.BuildTransaction(Boolean sign, SigHash sigHash)
   at NBitcoin.TransactionBuilder.EstimateFees(FeeRate feeRate)
   at NBitcoin.TransactionBuilder.SendEstimatedFees(FeeRate feeRate)
   at BTCLib.BTCCore.BuildAndSend(String address, Double amount, Double feesats)

Message:
A change address should be specified (Uncolored)

?????

**Comment by NicolasDorier** [comment]
Move `SetChange` above `SendEstimatedFees`
