### ISSUE TITLE
End of Stream Exception when creating ExtKey from restored Key - Hex and PrivateKey

### ISSUE THREAD

**Issue by sixjac** [MetacoSA/NBitcoin#543]
Hi,

I restored Key object with Private Key string, code below:

 Key k = Key.Parse(privateKey, network);
 ExtKey ext = new ExtKey(new ExtPubKey(k.PubKey.ToHex()), k.GetBitcoinSecret(network).PrivateKey); (Throws)

Upon attempting to create ExtKey it throws with message "No more byte to read".

below stack trace:
at NBitcoin.BitcoinStream.ReadWriteBytes(Byte[]& data, Int32 offset, Int32 count)
   at NBitcoin.ExtPubKey.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinSerializableExtensions.ReadWrite(IBitcoinSerializable serializable, Stream stream, Boolean serializing, Nullable`1 version)
   at NBitcoin.ExtPubKey..ctor(Byte[] bytes)
   at BTCLib.KeyManagement.Safe.ImportAsync(String privateKey, String password, String walletFilePath, String filename, Network network)

Maybe this is NBitcoin bug then again maybe I am using it incorrectly......

Thanks

**Comment by sixjac** [comment]
Solved it, my bad ;)
