### ISSUE TITLE
Building Altcoin Transcation on Android

### ISSUE THREAD

**Issue by Silverwizard80** [MetacoSA/NBitcoin#615]
Hi, I am using a modified NBitcoin.Altcoins Library, and a modified NBXplorer server to support my litecoin based altcoin. I am currently working on a cossplatform xamarin forms mobile solution using Net Standard 2.0. I am attempting to boardcast a transaction, but am not sure where I am going wrong here

            void SendTrans(object sender, EventArgs e)
            {
                var privatefolder = "PrivateKey15";
                var privatekypath = PortablePath.Combine(FileSystem.Current.LocalStorage.Path, privatefolder);
                var privatekeyfile = Directory.GetFiles(privatekypath);
                string result1 = ConvertStringArrayToString(privatekeyfile);
                var pkfile = System.IO.File.OpenText(result1);
                var pk = pkfile.ReadToEnd();

                var PrivateKey = pk;
                var network = new NBXplorerNetworkProvider(NetworkType.Mainnet).GetMAC();
                ExecKeyStore Recieved = JsonConvert.DeserializeObject<ExecKeyStore>(PrivateKey);
               	
                var userExtKey = new ExtKey(Recieved.ByteArray);

                //var userExtKey = new ExtKey();
                var userDerivationScheme = network.DerivationStrategyFactory.CreateDirectDerivationStrategy(userExtKey.Neuter(), new DerivationStrategyOptions()
                {
                    // Use non-segwit
                    Legacy = true
                });
                ExplorerClient client = new ExplorerClient(network);
                client.Track(userDerivationScheme);
                var utxos = client.GetUTXOs(userDerivationScheme);
		//ammountVMEENT is the entry box in my GUI
                var CoinsToSend = ammountVMEENT.Text;
                var AmmountToSend = decimal.Parse(CoinsToSend);
                while (true)
                {
                    var coins = utxos.GetUnspentCoins(true);
                    var keys = utxos.GetKeys(userExtKey, true);
                    var builder = AltNetworkSets.MyAltcoin.Mainnet.CreateTransactionBuilder();
                    builder.AddCoins(coins);
                    builder.AddKeys(keys);
		    //AdrENT is my entry box for the address
                    var addressx = ToAdrENT.Text.ToString();
                   
                    BitcoinScriptAddress x = new BitcoinScriptAddress(addressx, AltNetworkSets.MyAltcoin.Mainnet);
                    
                    builder.Send(x, Money.Coins(AmmountToSend));
                    var change = client.GetUnused(userDerivationScheme, DerivationFeature.Deposit).ScriptPubKey;
                    builder.SetChange(change);
                    //Set Fee
                    var fallbackFeeRate = new FeeRate(Money.Satoshis(1000), 1);
                    var feeRate = client.GetFeeRate(1, fallbackFeeRate).FeeRate;
                    builder.SendEstimatedFees(feeRate);
                    //Set Fee
                    var tx = builder.BuildTransaction(true);
                    var v = builder.Verify(tx);
                    var result = client.Broadcast(tx);
                    if (result.Success)
                    {
                        DisplayAlert("Notice","Transaction Was Suncessfully Sent","Close");
                        //Console.WriteLine("Success!");
                        break;
                    }
                    else if (result.RPCCode.HasValue && result.RPCCode.Value == RPCErrorCode.RPC_TRANSACTION_REJECTED)
                    {
                        //Console.WriteLine("We probably got a conflict, let's try again!");
                        DisplayAlert("Notice", "There was a conflict, Trying again", "Close");
                        continue;
                    }
                    else
                    {
                        DisplayAlert("Notice", $"Something is really wrong {result.RPCCode} {result.RPCCodeMessage} {result.RPCMessage}", "Close");
                        //Console.WriteLine($"Something is really wrong {result.RPCCode} {result.RPCCodeMessage} {result.RPCMessage}");
                        // Do something!!!
                    }
My code breaks at var result = client.Broadcast(tx); with Unhandled Exeption: "System.Net.Http.HttpRequestException: 500 (Internal Server Error)"
on the NBXplorer end I get the error:
"System.IO.EndOfStreamException: No more byte to read
   at NBitcoin.BitcoinStream.ReadWriteBytes(Span`1 data) in C:\Sources\NBitcoin\NBitcoin\BitcoinStream.cs:line 368
   at NBitcoin.BitcoinStream.ReadWriteNumber(UInt64& value, Int32 size) in C:\Sources\NBitcoin\NBitcoin\BitcoinStream.cs:line 305
   at NBitcoin.BitcoinStream.ReadWrite(UInt32& data) in C:\Sources\NBitcoin\NBitcoin\BitcoinStream.Partial.cs:line 378
   at NBitcoin.Transaction.ReadWrite(BitcoinStream stream) in C:\Sources\NBitcoin\NBitcoin\Transaction.cs:line 1367
   at NBXplorer.Controllers.MainController.Broadcast(String cryptoCode, DerivationStrategyBase extPubKey, DerivationStrategyBase derivationScheme, BitcoinAddress address) in /home/probetatesting/NBXplorer/NBXplorer/Controllers/MainController.cs:line 888
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)"

I am still pretty new to working with this library, and am not sure if this is a problem with my transaction, or with using these libraries in a mono environment. Thanks in advance.

**Comment by NicolasDorier** [comment]
Look the logs of NBXplorer

**Comment by knocte** [comment]
Hey @Silverwizard80 sorry to hijack this thread, but if you're building a XamarinForms wallet you may as well reuse some opensource code (MIT licensed) and/or collaborate with me, cause I started a project more than 1 year ago with this architecture in mind too, check it out: https://github.com/knocte/gwallet

**Comment by Silverwizard80** [comment]
Thank you for the quick replies, sorry it took me a while to write back. As for the F# implementation I did take a look, but am unfortunately not very familiar with F#. I downloaded the Gwallet frontend branch, but it crashed while generating the wallets. I would prefer to get this C# solution to work, but can't seem to find the issue. I get a fatal error when testing from my android phone in NBXplorer, but the transaction is received by NBXplorer when I use the same code on a command line application, and only gets rejected from mem pool. Not quite sure what to do here. Are there any logs separate from what appears in console, I couldn't find any elsewhere. I am using a linux platform for NBXplorer btw.

**Comment by knocte** [comment]
> I downloaded the Gwallet frontend branch, but it crashed while generating the wallets

Please file an issue with the crash details, in https://gitlab.com/DiginexGlobal/geewallet/issues and I will have a look. F# is not much different than C# if you read this guide: https://github.com/knocte/csharp2fsharp

> I am using a linux platform for NBXplorer btw

Maybe you're interested to know that geewallet also has a GTK frontend, which you can download from the artifacts of our CI build. e.g.: https://gitlab.com/DiginexGlobal/geewallet/-/jobs/132961043/artifacts/download

**Comment by Silverwizard80** [comment]
I was able to solve the issue by broadcasting the transaction directly over rpc instead of using NBXplorer.
