### ISSUE TITLE
Get balance return error

### ISSUE THREAD

**Issue by GnineWheel** [MetacoSA/NBitcoin#767]
An error message is returned when getting the balance: One or more errors occurred. I hope I can get your help. Thank you。

System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()

**Comment by nopara73** [comment]
Which function did you call?

**Comment by GnineWheel** [comment]
The GetBalance method returned an exception on Friday. It has now returned to normal.Below my code:
                let des = Util.Crypto.DES_decode(secret,des)
                let btcsecrt = des |> BitcoinSecret
                let network = btcsecrt.Network
                let address = btcsecrt.GetAddress()
                let client = new QBitNinjaClient(network)

                let balances = client.GetBalance(address).Result
