### ISSUE TITLE
Value cannot be null. (Parameter 'source') 

### ISSUE THREAD

**Issue by artem03** [MetacoSA/NBitcoin#967]
When I try create custom network I get exception.
There was no such problem in older versions of the library.
Now I use NBitcoin 5.0.73 version
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'source')
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NBitcoin.Network.Register(NetworkBuilder builder)
   at NBitcoin.NetworkBuilder.BuildAndRegister()
   at NBitcoin.NetworkSetBase.EnsureRegistered()
   at NBitcoin.NetworkSetBase.get_Mainnet()

**Comment by NicolasDorier** [comment]
hi @artem03 can you give me code to reproduce this error?

**Comment by artem03** [comment]
I solved the problem, I needed to add .SetGenesis (string genesis) to the creation of the network.
